package com.poketrek.moneo.correction

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/**
 * Lets the user propose a corrected Korean string for a sentence and pick
 * how to ship it (GitHub Issue, VPS, …). The dialog renders one button per
 * available [CorrectionSubmitter] in the confirm row; the caller does the
 * actual submit + Snackbar in a coroutine.
 *
 * The proposed-Korean field defaults to the current text so the user can
 * make a small edit instead of retyping. A blank or unchanged value sends
 * the report with `proposedKorean = null`, which the maintainer reads as
 * "I'm flagging this but didn't propose a fix."
 */
@Composable
fun CorrectionDialog(
    initialReport: CorrectionReport,
    submitters: List<CorrectionSubmitter>,
    onDismiss: () -> Unit,
    onSubmit: (CorrectionReport, CorrectionSubmitter) -> Unit,
) {
    var proposed by remember { mutableStateOf(initialReport.currentKorean) }
    var reason by remember { mutableStateOf("") }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("Suggest a correction") },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                Text(
                    "${initialReport.vocabHeadword} · ${initialReport.vocabGloss}",
                    fontSize = 12.sp,
                    color = Color(0xFF6B7280),
                )
                Text("Current Korean", fontWeight = FontWeight.SemiBold, fontSize = 12.sp)
                Text(initialReport.currentKorean, fontSize = 14.sp)
                Text("Current English", fontWeight = FontWeight.SemiBold, fontSize = 12.sp)
                Text(initialReport.currentGloss, fontSize = 13.sp, color = Color(0xFF374151))
                OutlinedTextField(
                    value = proposed,
                    onValueChange = { proposed = it },
                    label = { Text("Proposed Korean") },
                    modifier = Modifier.fillMaxWidth(),
                    singleLine = false,
                )
                OutlinedTextField(
                    value = reason,
                    onValueChange = { reason = it },
                    label = { Text("Why is this wrong? (optional)") },
                    modifier = Modifier.fillMaxWidth(),
                    singleLine = false,
                )
                if (initialReport.generator?.startsWith("llm-") == true) {
                    Text(
                        "AI-generated by ${initialReport.generator} — corrections especially welcome",
                        fontSize = 11.sp,
                        color = Color(0xFF6366F1),
                    )
                }
            }
        },
        confirmButton = {
            Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
                submitters.forEach { submitter ->
                    Button(
                        onClick = {
                            val cleanProposed = proposed
                                .takeIf { it.isNotBlank() && it != initialReport.currentKorean }
                            val cleanReason = reason.takeIf { it.isNotBlank() }
                            onSubmit(
                                initialReport.copy(
                                    proposedKorean = cleanProposed,
                                    reason = cleanReason,
                                ),
                                submitter,
                            )
                        },
                        modifier = Modifier.fillMaxWidth(),
                    ) {
                        Text(submitter.displayName)
                    }
                }
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) { Text("Cancel") }
        },
    )
}
